### ISSUE TITLE
npm ERR! Invalid name: "<%= moduleName %>" when trying to install

### ISSUE THREAD

**Issue by dmitriz** [sindresorhus/meow#21]
Getting this error when trying to install:
```
npm install --save meow
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "meow"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7

npm ERR! Invalid name: "<%= moduleName %>"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```
Here is debug-log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'meow' ]
2 info using npm@2.14.7
3 info using node@v4.2.3
4 verbose install initial load of /Volumes/Macintosh HD/Users/dmitrizaitsev/Dropbox/p/WebDev/Sandbox/Sindre-start-project/package.json
5 verbose stack Error: Invalid name: "<%= moduleName %>"
5 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:331:15)
5 verbose stack     at Object.module.exports.fixNameField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:210:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
5 verbose stack     at Array.forEach (native)
5 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
5 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:338:5)
5 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:232:12
5 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16
5 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
6 verbose cwd /Volumes/Macintosh HD/Users/dmitrizaitsev/Dropbox/p/WebDev/Sandbox/Sindre-start-project
7 error Darwin 14.5.0
8 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "meow"
9 error node v4.2.3
10 error npm  v2.14.7
11 error Invalid name: "<%= moduleName %>"
12 error If you need help, you may report this error at:
12 error     <https://github.com/npm/npm/issues>
13 verbose exit [ 1, true ]
npm-debug.log (END) 
```

**Comment by sindresorhus** [comment]
Well, yeah. You have to give it a proper name: https://github.com/sindresorhus/node-module-boilerplate/blob/8bc6c2673351629ad43eca4fd05101cd801337b9/cli-boilerplate/package.json#L2

I would recommend using https://github.com/sindresorhus/generator-nm which prompts you about this and fills in all the template placeholders.

**Comment by dmitriz** [comment]
Thanks, you are right of course :)
