### ISSUE TITLE
can not install with npm v3.8.9 (NodeJS v4.4.4)

### ISSUE THREAD

**Issue by alfalabs** [sindresorhus/meow#41]
npm install shows errors:
```
PS C:\> npm install -g meow
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin7\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\n
pm-cli.js" "install" "-g" "meow"
npm ERR! node v4.4.4
npm ERR! npm  v3.8.9
npm ERR! file C:\Users\admin7\AppData\Roaming\npm-cache\meow\3.7.0\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! No data, empty input at 1:1
npm ERR!
npm ERR! ^
npm ERR! File: C:\Users\admin7\AppData\Roaming\npm-cache\meow\3.7.0\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     C:\npm-debug.log
```
here is the npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\admin7\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'meow' ]
2 info using npm@3.8.9
3 info using node@v4.4.4
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData meow
8 silly fetchNamedPackageData meow
9 silly mapToRegistry name meow
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry data Result {
12 silly mapToRegistry   raw: 'meow',
12 silly mapToRegistry   scope: null,
12 silly mapToRegistry   name: 'meow',
12 silly mapToRegistry   rawSpec: '',
12 silly mapToRegistry   spec: 'latest',
12 silly mapToRegistry   type: 'tag' }
13 silly mapToRegistry uri https://registry.npmjs.org/meow
14 verbose request uri https://registry.npmjs.org/meow
15 verbose request no auth needed
16 info attempt registry request try #1 at 3:40:07 PM
17 verbose request id eea792ea4a83a85c
18 verbose etag "5EAEC0HULK1YO4DEWF66VEVH6"
19 http request GET https://registry.npmjs.org/meow
20 http 304 https://registry.npmjs.org/meow
21 verbose headers { date: 'Fri, 06 May 2016 19:40:10 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"5EAEC0HULK1YO4DEWF66VEVH6"',
21 verbose headers   age: '242',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-dfw1831-DFW',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '7',
21 verbose headers   'x-timer': 'S1462563610.276427,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Fri, 06 May 2016 19:40:10 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"5EAEC0HULK1YO4DEWF66VEVH6"',
22 silly get     age: '242',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-dfw1831-DFW',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '7',
22 silly get     'x-timer': 'S1462563610.276427,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/meow from cache
24 verbose get saving meow to C:\Users\admin7\AppData\Roaming\npm-cache\registry.npmjs.org\meow\.cache.json
25 verbose correctMkdir C:\Users\admin7\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
26 silly install normalizeTree
27 silly loadCurrentTree Finishing
28 silly loadIdealTree Starting
29 silly install loadIdealTree
30 silly cloneCurrentTree Starting
31 silly install cloneCurrentTreeToIdealTree
32 silly cloneCurrentTree Finishing
33 silly loadShrinkwrap Starting
34 silly install loadShrinkwrap
35 silly loadShrinkwrap Finishing
36 silly loadAllDepsIntoIdealTree Starting
37 silly install loadAllDepsIntoIdealTree
38 silly resolveWithNewModule meow@3.7.0 checking installable status
39 silly cache add args [ 'meow', null ]
40 verbose cache add spec meow
41 silly cache add parsed spec Result {
41 silly cache add   raw: 'meow',
41 silly cache add   scope: null,
41 silly cache add   name: 'meow',
41 silly cache add   rawSpec: '',
41 silly cache add   spec: 'latest',
41 silly cache add   type: 'tag' }
42 silly addNamed meow@latest
43 verbose addNamed "latest" is being treated as a dist-tag for meow
44 info addNameTag [ 'meow', 'latest' ]
45 silly mapToRegistry name meow
46 silly mapToRegistry using default registry
47 silly mapToRegistry registry https://registry.npmjs.org/
48 silly mapToRegistry data Result {
48 silly mapToRegistry   raw: 'meow',
48 silly mapToRegistry   scope: null,
48 silly mapToRegistry   name: 'meow',
48 silly mapToRegistry   rawSpec: '',
48 silly mapToRegistry   spec: 'latest',
48 silly mapToRegistry   type: 'tag' }
49 silly mapToRegistry uri https://registry.npmjs.org/meow
50 verbose addNameTag registry:https://registry.npmjs.org/meow not in flight; fetching
51 verbose get https://registry.npmjs.org/meow not expired, no request
52 silly addNameTag next cb for meow with tag latest
53 silly addNamed meow@3.7.0
54 verbose addNamed "3.7.0" is a plain semver version for meow
55 silly rollbackFailedOptional Starting
56 silly rollbackFailedOptional Finishing
57 silly runTopLevelLifecycles Starting
58 silly runTopLevelLifecycles Finishing
59 silly install printInstalled
60 verbose stack Error: Failed to parse json
60 verbose stack No data, empty input at 1:1
60 verbose stack
60 verbose stack ^
60 verbose stack     at parseError (C:\Users\admin7\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:390:11)
60 verbose stack     at parseJson (C:\Users\admin7\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:79:23)
60 verbose stack     at C:\Users\admin7\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:48:5
60 verbose stack     at C:\Users\admin7\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
60 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
61 verbose cwd C:\
62 error Windows_NT 6.1.7601
63 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin7\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "meow"
64 error node v4.4.4
65 error npm  v3.8.9
66 error file C:\Users\admin7\AppData\Roaming\npm-cache\meow\3.7.0\package\package.json
67 error code EJSONPARSE
68 error Failed to parse json
68 error No data, empty input at 1:1
68 error
68 error ^
69 error File: C:\Users\admin7\AppData\Roaming\npm-cache\meow\3.7.0\package\package.json
70 error Failed to parse package.json data.
70 error package.json must be actual JSON, not just JavaScript.
70 error
70 error This is not a bug in npm.
70 error Tell the package author to fix their package.json file. JSON.parse
71 verbose exit [ 1, true ]
```

**Comment by SamVerschueren** [comment]
First of all, why do you want to install it globally? There is no use in doing that. Second of all, if it fails to parse the JSON, it's a bug in npm.

**Comment by alfalabs** [comment]
@SamVerschueren 
the same error was installing it locally. There is a funny comment in npm message, please read it carefully:

`npm ERR! package.json must be actual JSON, not just JavaScript.`
`npm ERR! `
`npm ERR!` **This is not a bug in npm**.
`npm ERR! Tell the package author to fix their package.json file. JSON.parse`


which npm version will install this package?

**Comment by sindresorhus** [comment]
This is a problem with your system or npm. Try clearing the cache `npm cache clean`.
